GDC-755: Перенести репозитории в gazprom-neft
gazprom-neft/consta-widgets-configs pull request #2
Opened 2020-09-11 08:55 UTC by graberzz

2020-09-18 07:47 UTC, al-fyodorov requested changes

2020-09-18 07:47 UTC, al-fyodorov commented on package.json
> +  "version": "1.1.2-0",
А что тут означает версия 1.1.2-0, просто повышения версии патча не достаточно?

2020-09-18 07:48 UTC, al-fyodorov commented on package.json
> +  "version": "1.1.2-0",
И зачем вообще поднимать версию в PR, если ее все равно нужно будет поднять при публикации в registry?

2020-09-18 08:25 UTC, graberzz commented on package.json
> +  "version": "1.1.2-0",
В npm она уже опубликована, вообще можно было обойтись без бампа версии, но из-за некорректно опубликованного релиза в npm, где их нельзя удалять, выпустил препатч с фиксом, не стал выпускать патч, чтобы избежать возможных конфликтов при переезде, в случае если за это время успели бы опубликовать новую версию еще в GH Registry

2020-09-21 07:32 UTC, nekitk approved these changes

2020-09-21 07:33 UTC, nekitk commented on package.json
> +  "version": "1.1.2-0",
а зачем в пул-реквесте версию поднимать?
версию нужно поднимать в мастере после того, как пул-реквест вмёржим

2020-09-21 07:37 UTC, nekitk commented on package.json
> +  "version": "1.1.2-0",
насколько вижу, эта версия уже опубликована в npm, причём в latest тэг
так точно не нужно делать. версия в npm должна соответствовать тому, что в мастере репозитория. если хочешь выпустить бета-версию, то не нужно паблишить её в latest тэг npm-а и в любом случае не стоит ничего паблишить из пул-реквеста до того, как прошло ревью

2020-09-21 07:38 UTC, nekitk requested changes
https://github.com/gazprom-neft/consta-widgets-configs/pull/2#discussion_r491842410

2020-09-21 09:33 UTC, merged